### ISSUE TITLE
Port only published locally?

### ISSUE THREAD

**Issue by alexlouden** [escalate/ansible-raspberry-home-assistant-docker#1]
Hi,

Firstly - thanks so much for this! It was a breeze to get set up and running, and looks like exactly what I'm after.

I've noticed that the container port is only [published locally](https://github.com/escalate/ansible-raspberry-home-assistant-docker/blob/master/templates/home-assistant.service.j2#L27) - I was just wondering how I should then make that port accessible on the network? What do you use for your setup at home? 

Would you accept a PR that makes the into a var?

Thank you!

**Comment by escalate** [comment]
Hi @alexlouden,

Thank you very much for your support via PayPal.
I'm always happy to meet like-minded people and help them out.

You can see my Raspberry Pi setup here: https://github.com/escalate/my-smart-home/blob/master/host_vars/smarthome.fritz.box/vars.yml
I'm not a big fan of having to remember ports.
I prefer simple DNS names for my services e.g. home-assistant.xyz.com
For this reason I use Traefic as a reverse proxy.
Traefic communicates over an internal Docker network with the services.
So with this setup, it is enough if the services only listen on 127.0.0.1 to check with Ansible whether the services are fully deployed.

However, at the beginning I had thought about making the publish IP address configurable for others.
Therefore, it would be fine for me to include this.
I hope that helps you in your case.

Greetings
Felix

**Comment by alexlouden** [comment]
Great, thank you so much! Using Trafeic is a good idea - I'll consider that for the future, but for now this is a nice simple solution :)
